version: "2.2"

services:
    salt-master:
        build:
            context: . 
            dockerfile: Dockerfile.master
        image: dch/salt-master
    salt-minion:
        build:
            context: . 
            dockerfile: Dockerfile.minion
        image: dch/salt-minion
        depends_on: 
            - salt-master
        scale: 50

